### ISSUE TITLE
Broken download link for v1.2

### ISSUE THREAD

**Issue by OverdueFashion** [epicnyanpandi/SpotifyAdMuter#1]
The "download link" on the main page (https://github.com/enpandi/SpotifyAdMuter) is broken, 404 error for 
https://github.com/enpandi/SpotifyAdMuter/releases/download/v1.2/SpotifyAdMuter.exe

**Comment by enpandi** [comment]
I've made some changes, please try again. You will need all three files (`SpotifyAdMuter.dll`, `SpotifyAdMuter.exe`, and `SpotifyAdMuter.runtimeconfig.json`) to be in the same directory. I unfortunately was not able to figure out how to bundle everything into `SpotifyAdMuter.exe`.
